general {
    disable_loading_bar = true
    hide_cursor = true
}

background {
    monitor =
    path = /home/tosi4ka/.config/hypr/wallpaper
    blur_passes = 2
    blur_size = 5
    brightness = 0.7
}

# Время
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(ffffffff)
    font_size = 80
    font_family = JetBrains Mono Bold
    shadow_passes = 2
    shadow_size = 4
    position = 0, 180
    halign = center
    valign = center
}

# Дата
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" | python3 -c "
import sys
days = ['Понедельник','Вторник','Среда','Четверг','Пятница','Суббота','Воскресенье']
months = ['','января','февраля','марта','апреля','мая','июня','июля','августа','сентября','октября','ноября','декабря']
import datetime; d = datetime.date.today()
print(f'{days[d.weekday()]}, {d.day} {months[d.month]} {d.year}')
"
    color = rgba(cccccccc)
    font_size = 18
    font_family = JetBrains Mono
    shadow_passes = 1
    shadow_size = 3
    position = 0, 100
    halign = center
    valign = center
}

# Поле ввода
input-field {
    monitor =
    size = 320, 52
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.2
    outer_color = rgb(7f77dd)
    inner_color = rgb(14141c)
    font_color = rgb(cccccc)
    check_color = rgb(a3e3a3)
    fail_color = rgb(f09595)
    fail_text = <i>Неверный пароль</i>
    fade_on_empty = true
    placeholder_text = <span foreground="##666666"><i>Пароль...</i></span>
    hide_input = false
    rounding = 10
    position = 0, -80
    halign = center
    valign = center
}

# Раскладка
label {
    monitor =
    text = cmd[update:1000] hyprctl devices -j | python3 -c "import json,sys; kbs=[k for k in json.load(sys.stdin)['keyboards'] if 'virtual' not in k['name']]; km=kbs[-1]['active_keymap'] if kbs else ''; print('RU' if 'Russian' in km else 'EN')"
    color = rgba(7f77ddcc)
    font_size = 14
    font_family = JetBrains Mono Bold
    position = 0, -148
    halign = center
    valign = center
}
