splash = false
preload = /home/tosi4ka/SomeFiles/img/image045-33-1280x720.jpg
wallpaper = eDP-1,/home/tosi4ka/SomeFiles/img/image045-33-1280x720.jpg
preload = /home/tosi4ka/SomeFiles/img/image045-33-1280x720.jpg
wallpaper = HDMI-A-1,/home/tosi4ka/SomeFiles/img/image045-33-1280x720.jpg
